version: "3"

services:
  spark-standalone:
    build:
      context: .
      dockerfile: dockerfile.local
    container_name: spark-standalone
    ports:
      - "8080:8080"  # Spark UI
      - "4040:4040"  # Spark Application UI
    volumes:
      - ../src:/opt/spark-apps
      - ../data:/opt/data
    environment:
      - SPARK_MODE=standalone
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_IP=spark-standalone
      - SPARK_PUBLIC_DNS=localhost
    deploy:
      resources:
        limits:
          memory: 8G 